### ISSUE TITLE
[CRITICAL] Container not able to reach other containers within a docker network

### ISSUE THREAD

**Issue by ilan-schemoul** [zodern/meteor-up#1106]
Mup version (`mup --version`):
1.4.6
Mup config

```{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "root",
      "password": "password"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "https://host.com",
      "VIRTUAL_HOST": "pharmaciesousprefecture.fr,www.pharmaciesousprefecture.fr",
      "HTTPS_METHOD": "noredirect",
      "HTTP_FORWARDED_COUNT": 1,
      "LETSENCRYPT_HOST": "pharmaciesousprefecture.fr,www.pharmaciesousprefecture.fr",
      "LETSENCRYPT_EMAIL": "xd111@hotmail.fr"
    },
    "docker": {
      "image": "zodern/meteor:root",
      "networks": [
        "pharma"
      ],
      "stopAppDuringPrepareBundle": true
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "proxy": {
    "domains": "pharmaciesousprefecture.fr,www.pharmaciesousprefecture.fr",
    "ssl": {
      "letsEncryptEmail": "xd111@hotmail.fr"
    }
  }
}
✓ Config is valid

```
I have a container with mysql 
```
version: '3.5'

services:

  pharma-sql:
    container_name:
      pharma-sql
    ports:
      - 3306:3306
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./.ddb:/var/lib/mysql"
      - "./ddbbackup.sql:/docker-entrypoint-initdb.d/ddbbackup.sql"
    networks:
      - pharma
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD

  adminer:
    networks:
      - pharma
    image: adminer
    restart: always
    ports:
      - 8081:8080

networks:
  pharma:
    name: pharma
```

This mysql container lives in the same network called pharma as my meteor up container. Yet 
```
import Sequelize from 'sequelize';

const { name, user, password, host } = Meteor.settings.database;

console.log('HOST IS ' +host);

const db = new Sequelize(name, user, password, {
  host,
  port: 3306,
  dialect: 'mysql',
  logging: false,
});

db.sync({
  force: false,
});

export default db;
```

When I make a pure node docker container I attach to pharma it can successfully reach pharma-sql but not when it is inside a meteor up container
Inside a meteor up container the same code trying to connect to the mysql container reads " getaddrinfo ENOTFOUND pharma-sql pharma-sql:3306".
Why I can't access mysql container from a docker container made my meteor up but I can from one made myself ?
