### ISSUE TITLE
Question: Is the settings file included in the bundle?

### ISSUE THREAD

**Issue by Batistleman** [zodern/meteor-up#1142]
Is there anything from the settings.json file, or something from the mup.js that's included in the bundle? 

I would like to reuse the built bundle for multiple deploys, (by using --cached-build), but I'm unsure if I can do that.

My setup: 

```
server1: database_1, s3_1 (want to deploy master)
server2: database_1, s3_1 (eg. want to deploy one day/week later)
server3: database_2, s3_2 (etc.)
server4: database_3, s3_3 (etc.)
```

**Comment by zodern** [comment]
Neither are stored in the bundle, though some Mup plugins might store some information in it (such as [mup-cloud-front](https://www.npmjs.com/package/mup-cloud-front)). As long as the `app.buildOptions` can be the same for all apps it should work.

**Comment by Batistleman** [comment]
That's great, thanks!

**Comment by Batistleman** [comment]
<s>Perhaps a follow-up question: Is there a command to only build the bundle? (without requiring correct server / rool_url / mongo config / etc.)</s>

I just realised I could probably just use `meteor build` with the correct parameters, and use the output as input for the `--cached-build` correct?

Cfr.
https://github.com/zodern/meteor-up/blob/3c7120a75c12ea12fdd5688e33574c12e158fd07/src/plugins/meteor/build.js#L53

**Comment by zodern** [comment]
That is correct. You should also be able to use the hidden command `mup meteor build`.

**Comment by Batistleman** [comment]
That's great, thanks!

I'm now using a github action to compile every commit to master as a release file (we always deploy master to our servers). Building takes about 15 min, so now it will always be ready for download as an asset.

In case it could help you:

```
name: Create tag, release bundle.tar.gz on master push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.10.1'
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          release_name: Release ${{ steps.bump_version.outputs.new_tag }}
          body: This release is auto generated.
      - name: Install node_modules
        working-directory: ./app
        run: npm install
      - name: Build Meteor
        working-directory: ./app
        run: meteor build /tmp/build/ --architecture os.linux.x86_64
      - name: Upload Bundle as a release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/build/app.tar.gz
          asset_name: bundle.tar.gz
          asset_content_type: application/gzip

```
