### ISSUE TITLE
CI process

### ISSUE THREAD

**Issue by erperejildo** [zodern/meteor-up#574]
I'm currently using Gitlab CI to manage my tests, build and deploy. I was using Docker for this but I just got rid of it because was causing other problems.

Right now I'm using mup to make the deployment. So far I tried locally and it works (well, I've got another issues but at least it connect to my server so far).

So now I'm integrating this process on my Gitlab pipeline:
```
Deploy:
  image: node:latest
  stage: Deploy
  script:
    - curl "https://install.meteor.com/?release=1.4.2.6" | sh
    - chown -R $USER ~/.meteor
    - chown -R $USER .meteor/local
    - npm install -g mup
    - cd .deploy
    - mup setup
    - mup deploy
```

It's works.

But for this I need to storage my ssh key on my project folder and I don't want to do this (I put it on my private folder).
Gitlab provides the option to create variables (like $USER above) with for example a ssh key but the mup.json file needs the route for the ssh key and I can't use this. Either login with password because I disabled this on my server for security reasons. Only is possible with a ssh key.

Run `mup deploy` on my local machine is not an option for me. So my question here is how can I manage this process with a ssh key created by Gitlab?

**Comment by zodern** [comment]
Could you save it to a file using something like `echo $SSH_KEY > /path/to/ssh/key/in/config`?

**Comment by erperejildo** [comment]
Yes, I could but I don't want to storage my ssh key on my project. If is not possible to do this with Gitlab, ok, I'll do it like that

**Comment by zodern** [comment]
Sorry, I should have been more clear. You can add a step before `mup setup` for Gitlap Pipeline to save it in a file from the env variable.
```yml
Deploy:
  image: node:latest
  stage: Deploy
  script:
    - curl "https://install.meteor.com/?release=1.4.2.6" | sh
    - chown -R $USER ~/.meteor
    - chown -R $USER .meteor/local
    - npm install -g mup
    - cd .deploy
    - echo $SSH_KEY > ./ssh_key
    - mup setup
    - mup deploy
```
