### ISSUE TITLE
Deployment process

### ISSUE THREAD

**Issue by erperejildo** [zodern/meteor-up#584]
I'm setting up my deployment with Mup using it on Gitlab CI and I've got some doubts that I couldn't resolve online (this is not an issue itself).

I already have Nginx installed and configured with myApp.com.conf on /etc/nginx/sites-available and /sites-enabled:
```
server {
  listen                *:81;

  server_name           [myIP];

  access_log            /var/log/nginx/recipic.access.log;
  error_log             /var/log/nginx/recipic.error.log;

  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}

```

On my pipeline I've got this:
```
Deploy:
  image: node:6.9
  stage: Deploy
  script:
    - curl "https://install.meteor.com/?release=1.4.2.6" | sh
    - meteor npm install
    - meteor npm install --save angular-sanitize
    - meteor npm install --save bcrypt
    - npm install --unsafe-perm
    - npm -g install npm@latest-2
    - meteor npm rebuild
    - export METEOR_ALLOW_SUPERUSER=true
    - curl -L "https://www.npmjs.com/install.sh" | sh
    - npm install -g mup
    - cd .deploy
    - mup setup
    - meteor node -v
    - mup deploy
```

This install everything to deploy my Meteor app and get this output:
```
$ mup deploy
Building App Bundle Locally

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local


Started TaskList: Pushing Meteor App
[138.68.171.51] - Pushing Meteor App Bundle to The Server
[138.68.171.51] - Pushing Meteor App Bundle to The Server: SUCCESS

Started TaskList: Configuring App
[138.68.171.51] - Pushing the Startup Script
[138.68.171.51] - Pushing the Startup Script: SUCCESS
[138.68.171.51] - Sending Environment Variables
[138.68.171.51] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[138.68.171.51] - Start Meteor
[138.68.171.51] - Start Meteor: SUCCESS
[138.68.171.51] - Verifying Deployment
[138.68.171.51] - Verifying Deployment: SUCCESS
```
And also if I go to /opt/myAppName (this name is the one specified on my mup file on meteor --> name) this is the app uploaded.

But if I go to my website (just the IP because I don't have any domain yet) I can't see anything (also tried with port).
I'm using a droplet on DigitalOcean with 512RAM and 20GB with Ubuntu 16.04 and my Meteor version is 1.4.2.6

Is anything else I should do? 

Cheers mates!
